# @package _global_
description: "EPIC Timeline Passing"
make_timeline_video: True

use_old_sca: True                       # For cvpr submission, we use old sca, this is to keep-up with the old ones

# Stage control
which_only: 'fullpassing'              # one of {'fullpassing', 'static', 'inhand'}. 
                                       # i.e. Passing, A-only or C-only
segi_strategy: 'two-circle'            # one of {'normal', 'one-way', 'circle', 'two-circle'},
                                       # see potim/utils/propagation_helpers.py:segi_scheduler()
            
dataset:
    version: 'epic'
    json_path: ???
    skip_dynamic: False

    max_samples_per_seg: 30
    force_max_samples: True

    inhand_pose_init: 'learnt'           # Only useful for inhand_only. Or 'gt' or 'learnt-10' or 'learnt-6'

    static_init_method: 'multi_upright'

optim_mv:
    num_inits_parallel: 1

    optimize_obj_scale: True          # Different from e2e_v4, this should be true.

    # per epoch
    num_iters: 200 # 100, 200

    save_optim_video: False